variables:
  ###
  # IMPORTANT
  # These are the version tags for the docker images the CI runs against.
  # If you are hacking on them or need a them to rebuild, its enough
  # to change any part of the string of the image you want.
  ###
  FEDORA_TAG:  '2025-03-13.0'

  CHECKS_FEDORA_TAG: '2025-03-13.0'

  # FIXME: bump tag and rebuild image (and add branch suffix in .gitlab-ci.yml)
  ANDROID_FEDORA_TAG: '2024-11-01.0'

  UBUNTU_TAG: '2025-03-13.0'

  TESTS_UBUNTU_TAG: '2025-03-13.0'

  WINDOWS_IMAGE: 'registry.freedesktop.org/gstreamer/gstreamer/amd64/windows:2025-03-12.0-1.26'
