# ruff Python linter config file for cerbero project

line-length = 120
target-version = "py37"

[lint]
select = ["B006", "E4", "E7", "E9", "F", "FA102"]

[format]
# 5. Use single quotes for non-triple-quoted strings.
quote-style = "single"
